### ISSUE TITLE
Cannot pull image

### ISSUE THREAD

**Issue by CRASH-Tech** [bakito/sealed-secrets-web#12]
Cannot pull image, repo fail.
```
docker pull ghcr.io/bakito/sealed-secrets-web:v2.6.0
v2.6.0: Pulling from bakito/sealed-secrets-web
manifest unknown
```

**Comment by bakito** [comment]
@CRASH-Tech It seems something went wrong in the registry. I re-pushed the images for 2.6.0 and 2.6.1, can you retry?

**Comment by CRASH-Tech** [comment]
> @CRASH-Tech It seems something went wrong in the registry. I re-pushed the images for 2.6.0 and 2.6.1, can you retry?

Now it works. Thank!
