### ISSUE TITLE
Feature to validate sealed secrets via web and API

### ISSUE THREAD

**Issue by tiithansen** [bakito/sealed-secrets-web#127]
Currently it's possible to seal secrets through `/api/kubeseal` endpoint it would be nice to have `/api/validate` to validate existing sealed secrets. Kubeseal command line tool has option `--validate` which can be used to implement it.

**Comment by bakito** [comment]
Hi @tiithansen thank you very much for your request.

As I'm currently quite busy with other projects, I can't look into this immediately.

But in case you want to help, feel free ans open a pull request.

**Comment by rowi1de** [comment]
@tiithansen did you already start a PR? Maybe I can support you
