### ISSUE TITLE
Allow Custom Headers / Basic Auth for fetching cert.pem

### ISSUE THREAD

**Issue by rowi1de** [bakito/sealed-secrets-web#141]
- When using "certURL" it would be helpful to pass custom headers like basic auth
- It would be helpful if a secret could be referenced for that

**Comment by bakito** [comment]
Hi @rowi1de 

sealed-secrets-web is using the API (and client) from sealed-secrets which unfortunately does not allow to to define Headers.

**Comment by rowi1de** [comment]
Ok makes sense, I would need to create an Issue in their repo.
