### ISSUE TITLE
cannot seal when format yaml is used

### ISSUE THREAD

**Issue by dzabel** [bakito/sealed-secrets-web#16]
Hi,

First of all, thanks for implementing and maintaining this project.

I'm  using version `2.6.1` and i wanted switching to yaml format.

I have added this to the values

```
  args:
    - --kubeseal-arguments=--format=yaml
    - --format=yaml
```

So far, the inital secret is loaded as yaml. But if i try to seal it, i got this error:

```
{ "error": "invalid character 'a' looking for beginning of value" }
```

Did i miss something?

**Comment by bakito** [comment]
Hi @dzabel 

can you remove the --format argument from the --kubeseal-arguments?

the communication between sealed-secrets-web and kubeseal is via json and is formatted in the backend to yaml.

**Comment by dzabel** [comment]
Works perfect. Thank you!
