### ISSUE TITLE
Remove creationTimestamp: null for sealedSecrets

### ISSUE THREAD

**Issue by husira** [bakito/sealed-secrets-web#164]
Hi all,

Right now `metadata.creationTimestamp` and `spec.template.metadata.creationTimestamp` is always created after seal a secret in the web-ui.
<img width="1927" alt="image" src="https://github.com/bakito/sealed-secrets-web/assets/26415718/1d0456b4-3c60-4602-b1a7-393ec88d6e09">

Compared to older versions (for example 2.8.0), these fields have not been set.
<img width="1654" alt="image" src="https://github.com/bakito/sealed-secrets-web/assets/26415718/0ddea038-a057-4c69-b1b7-2670bc2c1f54">

We always remove these fields. Is there a possibility to remove these fields by default? Both values are set on the cluster when resources are applied.

p.s. By the way, I really like your project! The UI saves a lot of time when we need to seal secrets 👍

**Comment by bakito** [comment]
Hi @husira 
Thank you very much for the niche feedback. Much appreciated.

This application is using the default types form kubernetes and sealed-secrets and is also the default serialization.

The difference between v 2.8 and 3.x is that this application now uses the sealed secrets API and not it's cli binary any more.
This could explain the difference.

**Comment by bakito** [comment]
One option could be to do the cleanup in JavaScript on the client side.
