### ISSUE TITLE
RFE: secrets button without cluster role (single namespace use)

### ISSUE THREAD

**Issue by dzabel** [bakito/sealed-secrets-web#17]
First of all, very good job so far.

Situation:
* we have a multitenant cluster setup.
* we use sealed-secrets
* we like the decrypt feature for already sealed-secrets (secrets button upper right) 
* when we enable the "secret button" feature, we would give tenant "a" access to secrets from tenant "b" (e.g.) - due to the cluster role and cluster scope for secret retrieval

"What needs to be solved?"
* add an option for single namespace use
* when single namespace is configured:
* a `role` instead of a `cluster-role` is created
* a `role-binding` instead of a `cluster-role-binding` is created
* the scope for fetching the secrets is `namespace` instead of `cluster`

Any chance to get this feature?

**Comment by bakito** [comment]
Hi @dzabel 

Thank you for the FRE. this absolutely makes sens for me.

In https://github.com/bakito/sealed-secrets-web/pull/19 I've implemented a possible solution.

If you have any suggestions, improvements especially on naming values and arguments, feel free to add a comment.

Cheers

Marc

**Comment by 0x86f** [comment]
Hi @bakito, 

I had a look into your changes inside #19 and noticed one little issue (probably a leftover after the commit [rename value](https://github.com/bakito/sealed-secrets-web/pull/19/commits/685ebef42689c3c2faaf55c57df00bc71b6a1221)):
Passing `--local-namespace=%s` as an argument inside [_helpers.tpl](https://github.com/bakito/sealed-secrets-web/blob/local-namespace-only-mode/charts/sealed-secrets-web/templates/_helpers.tpl#L65) (when the variable `includeLocalNamespaceOnly ` is set to true) is never evaluated inside [types.go](https://github.com/bakito/sealed-secrets-web/blob/local-namespace-only-mode/pkg/config/types.go).

I would suggest to keep the use of `--local-namespace` as an additional argument and just evaluate it inside [Parse() in types.go](https://github.com/bakito/sealed-secrets-web/blob/local-namespace-only-mode/pkg/config/types.go#L25) right after `includeNamespaces`. The value of `--local-namespace` will then be added to `includeNamespaces` in case it's set.

Let me know what you think. Keep up the good work and happy new year!

**Comment by bakito** [comment]
Hi @0x86f thank you very much for your feedback.

I'd rather rename the argument in the helpers file to '--include-namespaces' and not define two arguments for (nearly) the same purpose.
