### ISSUE TITLE
Scope parameter in raw endpoint seems not working

### ISSUE THREAD

**Issue by mkschuel** [bakito/sealed-secrets-web#181]
Currently it's not possible to generate a sealed secret via the `/api/raw` endpoint for different scopes than the default one (strict).

The error seems to be in the 'Raw' function. Instead of using the predefined scope 
https://github.com/bakito/sealed-secrets-web/blob/d8d9dceec753f1a8035948a2764bd6e2621adf3f/pkg/seal/seal.go#L92-L95

the 'kubeseal.EncryptSecretItem' is called with 'v1alpha1.DefaultScope' again
https://github.com/bakito/sealed-secrets-web/blob/d8d9dceec753f1a8035948a2764bd6e2621adf3f/pkg/seal/seal.go#L98

Please ignore this analysis if I'm wrong. I'm not a Go developer.
Might be also that I'm used the API in a wrong way. This is how I used it:
```
curl --request POST 'https://<my-cluster-url>/api/raw' \                                                                ─╯
     --header 'Content-Type: application/json' \
     --data '{ "scope": "cluster-wide", "value": "value to seal" }'
```

PS: Anyway. Great tool. Thanks for sharing it.

**Comment by bakito** [comment]
Hi @mkschuel 

You're right, this seems not to work as expected.
Thank you very much for reporting.

I'll provide a new version ASAP
