### ISSUE TITLE
feat: Host charts on GitHub pages

### ISSUE THREAD

**Issue by mihaigalos** [bakito/sealed-secrets-web#183]
Would you consider hosting the charts on GH Pages instead of `charts.bakito.net`?
This would improve consumption of the charts via Helm, since GH is mostly a trusted source.

If yes, [here's](https://github.com/bitnami-labs/sealed-secrets/tree/gh-pages) how Bitnami does it: just create a branch called `gh-pages` and put the `index.yaml` there.

**Comment by bakito** [comment]
Hi @mihaigalos 
charts.bakito.net is running on github pages with a custom dns.
