### ISSUE TITLE
Readiness / Liveness Probe failed in EKS >= 1.27 

### ISSUE THREAD

**Issue by bobbykim-nsuslab** [bakito/sealed-secrets-web#192]
If you deploy sealed-secrets-web after deploying sealed-secrets in EKS 1.27, it will not run because the readiness/liveness probe is not connected as follows.

Looking at the code, it seems that sealed-secrets-web is not running properly because it is probably not connected to sealed-secrets.

![image](https://github.com/bakito/sealed-secrets-web/assets/133728942/a748cee6-5f70-47fc-a25b-37b4de3d1521)

As a result of my testing, 1.25 and 1.26 are properly connected to sealed-secrets and sealed-secrets-web listens to port 8080.

**Comment by bakito** [comment]
Hi @bobbykim-nsuslab 

Can you please provide logs of the sealed-secrets-web pod?

**Comment by bobbykim-nsuslab** [comment]
Log as below : 
```
2023/11/13 11:12:57 Connection to sealed secrets with (Namespace: sealed-secrets / ServiceName: sealed-secrets) 
```

And I thought there might be a relationship between the kuberntes version and sealed-secrets, but now even in 1.25 and 1.26, the readiness probe's connection refused occurs in sealed-secrets-web.

**Comment by bobbykim-nsuslab** [comment]
sealed-secrets and sealed-secrets-web are deployed in _sealed-secrets_ namespace

**Comment by bobbykim-nsuslab** [comment]
when I deploy sealed-secrets-web image as ricoberger chart image, it work

```
ealed-secrets-web-57b4c9654b-sj6l8 Starting "Sealed Secrets" Web Interface (version=2.4.0, branch=HEAD, revision=4b3da5aa32dc26f3108b3f38bf5473e45206d 
ealed-secrets-web-57b4c9654b-sj6l8 Build context (go=go1.16.7, user=runner, date=20210822-15:16:02)                                                    
ealed-secrets-web-57b4c9654b-sj6l8 Listening on :8080 
```

**Comment by bakito** [comment]
What versions of the helm chart and image are you using?

@bobbykim-nsuslab In your screen shot I see an image version 1.0.7  where does this come from?

**Comment by villadalmine** [comment]
annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: v0.23.0
description: Helm chart for the sealed-secrets controller.
home: https://github.com/bitnami-labs/sealed-secrets
icon: https://bitnami.com/assets/stacks/sealed-secrets/img/sealed-secrets-stack-220x234.png
keywords:
- secrets
- sealed-secrets
kubeVersion: '>=1.16.0-0'
maintainers:
- name: Bitnami
  url: https://github.com/bitnami-labs/sealed-secrets
name: sealed-secrets
type: application
version: 2.11.0

apiVersion: v2
appVersion: v3.1.3
description: A web interface for Sealed Secrets by Bitnami.
home: https://github.com/bakito/sealed-secrets-web
icon: https://raw.githubusercontent.com/bakito/sealed-secrets-web/master/assets/logo.png
maintainers:
- name: bakito
  url: https://github.com/bakito
name: sealed-secrets-web
version: 3.1.3

**Comment by villadalmine** [comment]
> Are any Network Policies in Place that prevent the k8s api from accessing the service in the sealed secrets namespace.
> 
> I don't have k8s 1.28 available. 1.27 works fine in e2e tests.

kubectl get networkPolicy -n ca43-sealed-secrets
No resources found in ca43-sealed-secrets namespace.

`
image:
  # --  Repository to use
  repository: xxxx/bakito/sealed-secrets-web
  #repository: xxx/ricoberger/sealed-secrets-web
  #tag: 2.4.0
  # -- Overrides the image tag (default is the chart appVersion)

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

sealedSecrets:
  # -- Namespace of the sealed secrets service
  namespace: ca43-sealed-secrets
  # -- Name of the sealed secrets service
  serviceName: sealed-secrets-tst-blue-se


ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: "180"
  hosts:
    - paths:
        - path: /
          pathType: Prefix
      host: sxxxxx




deployment:

  env:
    sealedSecretsControllerNamespace: ca43-sealed-secrets
    #sealedSecretsControllerName: sealed-secrets-tst-blue-se-7c458cfcf-xhpk7
`

If i comment all 

deployment:
  # -- Readiness Probes
  readinessProbe:
    failureThreshold: 3
    # periodSeconds: 5
    # successThreshold: 1
    # timeoutSeconds: 10
    # initialDelaySeconds: 30
    httpGet:
      path: /_health
      port: http

  # -- Liveness Probes
  livenessProbe:
    failureThreshold: 3
    # periodSeconds: 10
    # successThreshold: 1
    # timeoutSeconds: 10
    # initialDelaySeconds: 15
    httpGet:
      path: /_health
      port: http


Apps  go green, but nothing happend at ingress or log in the pod.

Any other idea where to check...
Im doing it to make developer happy, kubeseal for me it is ok :)

**Comment by bakito** [comment]
I managed to extend the e2e test to run on multiple k8s versions.
https://github.com/bakito/sealed-secrets-web/actions/runs/6852837207

Here all works.

Hard to tell what the issues on your clusters might be.

**Comment by JesusRo** [comment]
Hey guys, my 2 cents here. 

I had the very same issue (I mean, very same symptoms) on a public cloud provider, while same chart/version on an on-premise installation had no trouble at all.

The problem was that I had a firewall rule blocking the communication from k8s masters to sealed-secret port (actually, the cloud provider had it by default, only allowing 443 and 10250).

Would you mind to check if k8s API server (k8s master nodes) are able to reach service/pod IP at desired port (8080 by default) ?

Kr.

**Comment by villadalmine** [comment]
Yes, maybe i need to check, but it is not clear what is doing the binary in the pod of sealed-secret-web. What endpoint are try to consume in the readiness and liveness probe, because the svc used as input is part of the same ns and no network policy, do you have any reference to the code of the binary or more verbose log to understand what is doing that health check, maybe can help to understand what is happening inside my connection, im using cilium .

**Comment by JesusRo** [comment]
Hey,

In my case, was not an issue caused by sealed-secet-web binary, but by the cloud provider itself, which configures `enable-aggregator-routing` by default. This makes the masters to bypass the service and communicate straight to the POD (instead doing so by kube-proxy) and so, firewall doing its job not allowing port 8080

When sealed-secrets-web asks (to kubernetes svc) for the sealed-secret service, k8s API server tries to reach pod:port and gets a timeout. This leaves sealed-secret-web hanging for the reply, until the probes eagerly kill it.

In my case, what gave me more clues, was to completely remove the probes. This allowed sealed-secret-web to reach timeout on its call, and then did show more logs about issues fetching cert at sealed-secret service.

You may do that test too.
Also, check api-server logs on cloudwatch, they may show something

good luck :)

**Comment by villadalmine** [comment]
> Hey,
> 
> In my case, was not an issue caused by sealed-secet-web binary, but by the cloud provider itself, which configures `enable-aggregator-routing` by default. This makes the masters to bypass the service and communicate straight to the POD (instead doing so by kube-proxy) and so, firewall doing its job not allowing port 8080
> 
> When sealed-secrets-web asks (to kubernetes svc) for the sealed-secret service, k8s API server tries to reach pod:port and gets a timeout. This leaves sealed-secret-web hanging for the reply, until the probes eagerly kill it.
> 
> In my case, what gave me more clues, was to completely remove the probes. This allowed sealed-secret-web to reach timeout on its call, and then did show more logs about issues fetching cert at sealed-secret service.
> 
> You may do that test too. Also, check api-server logs on cloudwatch, they may show something
> 
> good luck :)

thanks, yes i will give a try, in my case i do not have kube-proxy . First time having this issues, i am able to apply any sealedSecret with kubectl, but  trying to understand if the health check is related also with the availability of sealed-secret-web to fetch public certificated from svc of sealed secret. No idea how is performing  the request, maybe i need to replicate that query manually inside the pod or something like that. Also no idea why pod need to use kube-api if in the definition im pointing directly to svc of sealed secret. So many stuff to test.. Just asking.. what happen after i have it working, because im installing it because i want a more friendly way for developers to seal their secrets...not sure if it is necessary to use any OIDC .. not sure how is working the webapp

**Comment by bobbykim-nsuslab** [comment]
> What versions of the helm chart and image are you using?
> 
> @bobbykim-nsuslab In your screen shot I see an image version 1.0.7 where does this come from?

**Comment by bobbykim-nsuslab** [comment]
> What versions of the helm chart and image are you using?
> 
> @bobbykim-nsuslab In your screen shot I see an image version 1.0.7 where does this come from?

I rebuilded and push on our private repository.

I install a helm chart using bakito/sealed-secrets-web. log as below:

```
  Containers:
  sealed-secrets-web:
    Container ID:  containerd://a8750cd31aad19d3baf9849a4c87a3638c44d1e5dc4234da0b6610d618a404f7
    Image:         ghcr.io/bakito/sealed-secrets-web:v3.1.3
    Image ID:      ghcr.io/bakito/sealed-secrets-web@sha256:451837252ce5e868cc7f1cee4ae483fc20ae0174261b8ed3d5f6f4d8413f0545
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --sealed-secrets-service-namespace=sealed-secrets
      --sealed-secrets-service-name=sealed-secrets
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Tue, 14 Nov 2023 10:00:25 +0900
      Finished:     Tue, 14 Nov 2023 10:00:54 +0900
    Ready:          False
    Restart Count:  6
    Liveness:       http-get http://:http/_health delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http/_health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-q82fn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-q82fn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  5m34s                   default-scheduler  Successfully assigned sealed-secrets/sealed-secrets-web-79b87c5665-6dfw2 to ip-192-168-32-135.ap-northeast-2.compute.internal
  Normal   Pulled     5m4s (x2 over 5m33s)    kubelet            Container image "ghcr.io/bakito/sealed-secrets-web:v3.1.3" already present on machine
  Normal   Created    5m4s (x2 over 5m33s)    kubelet            Created container sealed-secrets-web
  Normal   Killing    5m4s                    kubelet            Container sealed-secrets-web failed liveness probe, will be restarted
  Normal   Started    5m3s (x2 over 5m33s)    kubelet            Started container sealed-secrets-web
  Warning  Unhealthy  4m34s (x12 over 5m33s)  kubelet            Readiness probe failed: Get "http://192.168.32.202:8080/_health": dial tcp 192.168.32.202:8080: connect: connection refused
  Warning  Unhealthy  4m34s (x6 over 5m24s)   kubelet            Liveness probe failed: Get "http://192.168.32.202:8080/_health": dial tcp 192.168.32.202:8080: connect: connection refused
  Warning  BackOff    23s (x11 over 3m4s)     kubelet            Back-off restarting failed container
  ```

**Comment by villadalmine** [comment]
> I managed to extend the e2e test to run on multiple k8s versions. https://github.com/bakito/sealed-secrets-web/actions/runs/6852837207
> 
> Here all works.
> 
> Hard to tell what the issues on your clusters might be.

I just did some test, removed health_chec

`2023/11/14 08:16:59 Connection to sealed secrets with (Namespace: ca43-sealed-secrets / ServiceName: sealed-secrets-tst-blue-se)2023/11/14 08:17:29 Setup sealer: cannot fetch certificate: error trying to reach service: dial tcp 10.233.70.138:8080: i/o timeout
`
So i guess it is related with that service..


```
kubectl get svc -n ca43-sealed-secrets
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
sealed-secrets-tst-blue-se       ClusterIP   10.233.41.213   <none>        8080/TCP   98d
sealed-secrets-web-tst-blue-se   ClusterIP   10.233.31.15    <none>        5080/TCP   17h

```
also changed the port just in case..

Can you update the helm chart to get that functionality ?
Not sure where comes that ip in port 8080


```
 kubectl get pod -n ca43-sealed-secrets -o wide
NAME                                              READY   STATUS    RESTARTS      AGE     IP              NODE                              NOMINATED NODE   READINESS GATES
sealed-secrets-tst-blue-se-7c458cfcf-xhpk7        1/1     Running   0             61d     10.233.70.138   xxx   <none>           <none>
sealed-secrets-web-tst-blue-se-5498dfd978-zlsbc   0/1     Error     4 (97s ago)   4m27s   10.233.70.155   xxx   <none>           <none>
```

and the issue is related with the endpoint of sealed secret, no idea why is blocked

```
kubectl get endpoints -n ca43-sealed-secrets 
NAME                             ENDPOINTS            AGE
sealed-secrets-tst-blue-se       10.233.70.138:8080   38s
sealed-secrets-web-tst-blue-se                        89s
```

i saw a bug  for fetching secret but looks old, but i do not have sealed-secrets in kube-system,
so @bakito  i guess it is working fine your solution, i need to fix from my side.

Regards
Rino

**Comment by villadalmine** [comment]
> Hey,
> 
> In my case, was not an issue caused by sealed-secet-web binary, but by the cloud provider itself, which configures `enable-aggregator-routing` by default. This makes the masters to bypass the service and communicate straight to the POD (instead doing so by kube-proxy) and so, firewall doing its job not allowing port 8080
> 
> When sealed-secrets-web asks (to kubernetes svc) for the sealed-secret service, k8s API server tries to reach pod:port and gets a timeout. This leaves sealed-secret-web hanging for the reply, until the probes eagerly kill it.
> 
> In my case, what gave me more clues, was to completely remove the probes. This allowed sealed-secret-web to reach timeout on its call, and then did show more logs about issues fetching cert at sealed-secret service.
> 
> You may do that test too. Also, check api-server logs on cloudwatch, they may show something
> 
> good luck :)

I saw this from kubeseal, so i guess it is using kubeseal the kube-api to reach it, so now it is more clear.. so i guess sealed-secret-webs it is also using it

```
xx~/repos/azuredevops/vcs-k8s-core-services$ kubeseal --fetch-cert -v 10000 --controller-name sealed-secrets-tst-blue --controller-namespace ca43-sealed-secrets
I1114 11:04:53.963521 1365445 loader.go:373] Config loaded from file:  /xx/tst-blue-se-admin.yaml
I1114 11:04:53.964187 1365445 round_trippers.go:466] curl -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://apiserver.xx:6443/api/v1/namespaces/ca43-sealed-secrets/services/sealed-secrets-tst-blue'
I1114 11:04:53.965330 1365445 round_trippers.go:495] HTTP Trace: DNS Lookup for apiserver.xx resolved to [{10.40.136.28 }]
I1114 11:04:53.999798 1365445 round_trippers.go:510] HTTP Trace: Dial to tcp:10.40.136.28:6443 succeed
I1114 11:04:54.078084 1365445 round_trippers.go:553] GET https://apiserver.xx:6443/api/v1/namespaces/ca43-sealed-secrets/services/sealed-secrets-tst-blue 404 Not Found in 113 milliseconds
I1114 11:04:54.078108 1365445 round_trippers.go:570] HTTP Statistics: DNSLookup 1 ms Dial 34 ms TLSHandshake 41 ms ServerProcessing 36 ms Duration 113 ms
I1114 11:04:54.078125 1365445 round_trippers.go:577] Response Headers:
I1114 11:04:54.078136 1365445 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 1be80338-af35-4704-9e35-f6b677195c12
I1114 11:04:54.078146 1365445 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: 16ae5c5c-d5f0-4bb0-a55c-5ac26eac1fda
I1114 11:04:54.078156 1365445 round_trippers.go:580]     Content-Length: 222
I1114 11:04:54.078163 1365445 round_trippers.go:580]     Date: Tue, 14 Nov 2023 10:04:54 GMT
I1114 11:04:54.078172 1365445 round_trippers.go:580]     Audit-Id: 58bb163a-8ff1-4579-a13e-4a668ad2dd8e
I1114 11:04:54.078182 1365445 round_trippers.go:580]     Cache-Control: no-cache, private
I1114 11:04:54.078191 1365445 round_trippers.go:580]     Content-Type: application/json
I1114 11:04:54.078224 1365445 request.go:1188] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"sealed-secrets-tst-blue\" not found","reason":"NotFound","details":{"name":"sealed-secrets-tst-blue","kind":"services"},"code":404}
error: cannot get sealed secret service: services "sealed-secrets-tst-blue" not found.
Please, use the flag --controller-name and --controller-namespace to set up the name and namespace of the sealed secrets controller
```
i have something to check and fix :)

**Comment by villadalmine** [comment]
> sealed secrets web is using the api of sealed secrets via it's service to seal / unseal the secrets. Hence it needs to be able to connect to this service. Service information (sealedSecrets.serviceName, sealedSecrets.namespace) can be configured in the helm chart. See https://artifacthub.io/packages/helm/bakito/sealed-secrets-web

Yes, im using internal service but still having same issue like kubeseal reaching the kube-apiserver.


```
deployment:

  
  env:
    sealedSecretsControllerNamespace: ca43-sealed-secrets
    sealedSecretsControllerName: sealed-secrets-tst-blue-se

sealedSecrets:
  # -- Namespace of the sealed secrets service
  namespace: ca43-sealed-secrets
  # -- Name of the sealed secrets service
  serviceName: sealed-secrets-tst-blue-se

kubectl get svc -n ca43-sealed-secrets
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
sealed-secrets-tst-blue-se       ClusterIP   10.233.41.213   <none>        8080/TCP   98d
sealed-secrets-web-tst-blue-se   ClusterIP   10.233.31.15    <none>        5080/TCP   20h

$ kubectl get endpoints -n ca43-sealed-secrets
NAME                             ENDPOINTS            AGE
sealed-secrets-tst-blue-se       10.233.70.100:8080   135m
sealed-secrets-web-tst-blue-se                        136m


```

but pod still having issue

```
2023/11/14 10:40:50 Connection to sealed secrets with (Namespace: ca43-sealed-secrets / ServiceName: sealed-secrets-tst-blue-se)2023/11/14 10:41:20 Setup sealer: cannot fetch certificate: error trying to reach service: dial tcp 10.233.70.100:8080: i/o timeout
```

So for me the binary for sealed-secrets-web it is using kube-apiserver instead of internal api of sealed-secrets, i do not have any issue with sealed-secrets, im able to seal everything..


Looks like or binary is using api from outsiude or i have another issue.. but no networkpolicy at all from my side.

Regards
Rino

**Comment by villadalmine** [comment]
@bakito Im just enable ingress to fetch the certificate, 

but not sure how i need to add the correct value for env

flag provided but not defined: -sealed-secrets-cert-url https://ss.xxx/v1/cert.pemUsage of /opt/go/sealed-secrets-web:  -config string    	Define the config file

**Comment by anshuman852** [comment]
what was the fix for this? @bobbykim-nsuslab i am also having this issue on eks 1.28
