### ISSUE TITLE
Request: Authentication Support  OIDC

### ISSUE THREAD

**Issue by villadalmine** [bakito/sealed-secrets-web#196]
Hi,

Im really happy with your app!! and of course your help!!

I want to know if it is possible to add any kind of oidc support, in my case we are using ADFS from Microsoft but i can also use Registration APPs from azure AD or dex just in case connecting with ldap.

My request is related because i like the approach of load sealed secrets and also the option to load only for  NS.
So all customer are the owner of their NS, so i want to grant permission to read their sealed secret and not the entire system. I know i can deploy each sealed secret per namespace and setup to read only for that NS, but i have many NS for customer apps, and then i want to use one for us , only for infra admin.

Does it possible, make sense ??

Regards
Rino

**Comment by bakito** [comment]
Please check https://github.com/oauth2-proxy/oauth2-proxy

**Comment by villadalmine** [comment]
> Please check https://github.com/oauth2-proxy/oauth2-proxy

Nice, we are using ADFS for everything, and looks like that one can connect, to ADFS, i will check, im trying to do everything KISS, some solution like keycloack make more and more complex k8s, thanks for the feedback

**Comment by villadalmine** [comment]
But, i guess my problem is about permission, beucase i can grant access with ADFS to reach access to sealed-secret-web, but the app has access to all secret. In order to use that AUTH method and ns get access to their  secrets, i need to install one sealed-secret-web per NS.
For example.

I have one sealed secret web installed, with access to  secrets in  NS A,B,C.
I have that auth-proxy, then i can setup each RBAC per NS to reach access to the url of sealed-secret-web, but at the end  they will see all secrets in the NS.

But if install each sealed-secret-web per ns, i can solve my issue, but installing many sealed-secret-web..


SO i guess it is not so trivial and depend the case, im fine to get developer happy encoding/decoding their secrets , but i need time to understand and apply my case of use with some tools, so i guess nothing to do from sealed-secrets-web, it is not necessary to implement extra function to get kind of RBAC based in who used it.
