### ISSUE TITLE
ghcr.io: Backoff pulling image

### ISSUE THREAD

**Issue by mihaigalos** [bakito/sealed-secrets-web#217]
Hi there,

In my k3s, I see pods cannot pull the `ghcr.io/bakito/sealed-secrets-web:v3.1.4` container image. I assume this is because I have no secret set up to authenticate against ghcr.

Is there any easy way around this? - I don't want to have a token lying around in a cluster, if possible.

Are you also publishing images to a different container registry that doesn't require authentication first?

**Comment by bakito** [comment]
Images are also available at quai quay.io/bakito/sealed-secrets-web

**Comment by bakito** [comment]
But there's no release v3.1.4 yet, so there's no image to pull

**Comment by mihaigalos** [comment]
Aaa. I looked at `charts/`, took whatever was there. Thanks for the info! 😄

**Comment by mihaigalos** [comment]
Confirmed working, thank you! 👍

**Comment by bakito** [comment]
The chart.yaml  in the repo points to the netx versiom, please use the helm repo as documented in the Readme.
