### ISSUE TITLE
Multiple input Secrets?

### ISSUE THREAD

**Issue by mihaigalos** [bakito/sealed-secrets-web#245]
Running `v3.0.0`, we have the problem of not being able to input multiple Secrets for generating SealedSecrets.
Any chance to support this for the future?

I mean the output doesn't have to be sealed in 1 go. It can be sealed for each secret and the output concatenated to the result.

**Comment by bakito** [comment]
Hi @mihaigalos 
No there are currently no plans for this.

**Comment by mihaigalos** [comment]
Okok, no problem. Do you think I could have a look and potentially implement this?

**Comment by bakito** [comment]
Would you be willing to create a pull request?

**Comment by mihaigalos** [comment]
Had a deeper look, seems the bitnami [kubeseal](https://github.com/bitnami-labs/sealed-secrets/blob/main/pkg/kubeseal/kubeseal.go#L229) implementation can handle slices.

So this means the input can be multiple `kind: Secret`, if I understand correctly - at least from kubeseal's point of view.

**Comment by mihaigalos** [comment]
Also, seems the problem comes from [unsealing](https://github.com/bitnami-labs/sealed-secrets/blob/985008ede7fa8a2c16d8baf792d4dc13a01176a1/pkg/controller/controller.go#L499) not sealing per se, because it cannot unseal a multi-yaml input..
