### ISSUE TITLE
Question: Update libaries ( sealed-secrets ) to v0.27

### ISSUE THREAD

**Issue by Tilusch** [bakito/sealed-secrets-web#258]
Is there a plan to update the sealed-secrets library to v0.27 and deliver a new release?

**Comment by bakito** [comment]
Hi
This was merged yesterday to main: https://github.com/bakito/sealed-secrets-web/commit/01c03c7ac33cd5abe669b6b2040c6f92fc8f5c1d

Is there a special reason for the question?

**Comment by Tilusch** [comment]
Hi,
 
We wanted to upgrade our used sealed-secret operator to v0.27. So that the sealed-secret UI is in sync with the same version as the operator, I wanted to ask if this repo already include v0.27.
Usually we don't reference directly the main branch, normally we use releases/tags and this repo hasn't been tagged for a while. But if this is no longer planned we will reference the main branch.
Thank you for your quick reply.

**Comment by bakito** [comment]
Version https://github.com/bakito/sealed-secrets-web/releases/tag/v3.1.4 uses v0.27
