### ISSUE TITLE
[Enhancement] Usage/show yaml instead json

### ISSUE THREAD

**Issue by JesusRo** [bakito/sealed-secrets-web#29]
Hi there,

First, great tool.

Could be posible to have json-yaml swtich button or similar on the UI.
In most cases, for me, we have a yaml secret which needs to be converted into a yaml sealed-secret.

Right now, I´m converting yaml to json separatelly and viceversa, but would be cool to do it all at once.

Thanks in advance.
Kr,

**Comment by TechnicallyJoe** [comment]
This would be a nice feature. We much prefer yml to json

**Comment by TechnicallyJoe** [comment]
@JesusRo  If you are not using json at all, you can switch it to yaml using the image.args value "--format=yaml" 

 `helm upgrade --install sealed-secrets-web bakito/sealed-secrets-web --set "image.args={--format=yaml}"
`
Just figured that out myself :)

**Comment by JesusRo** [comment]
Hey @TechnicallyJoe,
Yeah indeed, forgot to come back here.
That´s the way I´m using now with yaml thanks

Also saw this, https://github.com/bakito/sealed-secrets-web/blob/main/pkg/config/types.go#L14
which I use for the other question on https://github.com/bakito/sealed-secrets-web/issues/34

I guess, we can close this
