### ISSUE TITLE
[Enhancement] Add authentication support

### ISSUE THREAD

**Issue by JesusRo** [bakito/sealed-secrets-web#30]
Hi again,

It would be awesome to have some sort of authentication, from basic user/pass to even better k8s auth token.
With last option, it would be also posible then to use that authentication against k8s so user can only see/manage the resource he has access to.

Thanks and regards

**Comment by bakito** [comment]
Hi 

The current implementation uses the service account token together with the sealed secret cli to seal and unseal sealed secrets.
Getting a token of the user might be tricky, at least, currently I don't know how this could be done.

As work-around you could use a sidecar such as https://github.com/dexidp/dex  do do authendication.

**Comment by JesusRo** [comment]
Just in case someone else arrive here.
I´m using https://github.com/xsc/nginx-sidecar-basic-auth for just user/pass authentication. Preatty simple
Still pending to test further dex :)
