### ISSUE TITLE
Optionally disable decrypt function?

### ISSUE THREAD

**Issue by TechnicallyJoe** [bakito/sealed-secrets-web#34]
Hi

I was looking at this tool because I don't want to give the developers / team members access to the cluster to encrypt the secrets. However, I don't want them to be able to take previously encrypted secrets and decrypt them - either. I'm worried about the security implications

Is there any way to disable the decrypt options entirely? A helm argument perhaps?

**Comment by JesusRo** [comment]
Hi @TechnicallyJoe,

Trying to pay you back from the other issue ;)

On the same place
https://github.com/bakito/sealed-secrets-web/blob/main/pkg/config/types.go#L14
I found we can disable "secreat reading", so the tool just fits on my needs.

It allows to seal yamls, and nothing else.
Also, I ensured sa has no permissions to read secrets, just in case.

These are the args I´m using:
```yaml
  args: 
  - "-disable-load-secrets"
  - "-format"
  - "yaml"
```

**Comment by TechnicallyJoe** [comment]
Very nice! - The author thought of a few things here, clearly! - If only they were documented @bakito ? :D 

I appreciate it @JesusRo  I'll try it out.

Out of curiousty - Is there any reason to have -format and yaml on separate lines?

**Comment by JesusRo** [comment]
> @JesusRo Obviously I didn't doubt you! but i just tested it and it works! Thank you very much!
xD doubt everything always, test it yourself and you will be always safe ;)

No actual reason for the usage of the args in that way tbh. Just I was using my own templates

I´ll try to document this and your helms examples and send a PR

thanks mate!

**Comment by JesusRo** [comment]
@TechnicallyJoe 
JFYI https://github.com/bakito/sealed-secrets-web/pull/35
