### ISSUE TITLE
[Question] How can I edit the initial secret yaml?

### ISSUE THREAD

**Issue by brunocascio** [bakito/sealed-secrets-web#48]
I would like to remove the placeholder initial secret and use for example cluster-wide secrets, where the namespace is not required/used for encryption.

For that, I would like to add my own secret template. I was reviewing the code but it's not clear to me how can I do it without making any change on this repo.

Thanks!

**Comment by bakito** [comment]
Hi @brunocascio 

There is a posibility.

You can create a configmap with the content of your initial secret template and mount it tot the deployment at any path.
Then you can extend the container args in the deployment with:

```
- "-initial-secret-file"
- "<path-to-mounted-secret-template>"
```

https://github.com/bakito/sealed-secrets-web/blob/main/pkg/config/types.go#L18
https://github.com/bakito/sealed-secrets-web/blob/main/charts/sealed-secrets-web/values.yaml#L16

**Comment by brunocascio** [comment]
> Hi @brunocascio
> 
> There is a posibility.
> 
> You can create a configmap with the content of your initial secret template and mount it tot the deployment at any path. Then you can extend the container args in the deployment with:
> 
> ```
> - "--initial-secret-file"
> - "<path-to-mounted-secret-template>"
> ```
> 
> https://github.com/bakito/sealed-secrets-web/blob/main/pkg/config/types.go#L18 https://github.com/bakito/sealed-secrets-web/blob/main/charts/sealed-secrets-web/values.yaml#L16

Got it! Thank you so much 🤙
