### ISSUE TITLE
Installation failed with `ErrImagePull` due to incorrectly constructed deployment image path

### ISSUE THREAD

**Issue by chgl** [bakito/sealed-secrets-web#8]
Thank you for continuing to work on this useful project!

There is one small bug in the helm chart causing installation to fail: `Chart.appVersion` is used to construct the image location, however it seems like the `v`-prefix is stripped from the appVersion in the repository's index.yaml: https://bakito.github.io/helm-charts/index.yaml. So instead of `ghcr.io/bakito/sealed-secrets-web:v2.6.0` the deployment image is set to `ghcr.io/bakito/sealed-secrets-web:2.6.0` causing installation to fail with an `ErrImagePull`.

I'm not sure where this happens since https://github.com/bakito/sealed-secrets-web/blob/main/charts/sealed-secrets-web/Chart.yaml#L2 does contain the `v`-prefix. I'd be happy to contribute if pointed at the right direction.

**Comment by bakito** [comment]
@chgl sorry for the long delay. I could fix the error and released a proper image and chart with 2.6.1
