### ISSUE TITLE
Add options to scope the secret

### ISSUE THREAD

**Issue by diptripa** [bakito/sealed-secrets-web#92]
Can we add an option to scope the secret to either a particular namespace or have it cluster scoped.

**Comment by bakito** [comment]
Hi @diptripa 
I'm not sure what you mean. Can you please explain your request more. E.g. add some examples of the expected result?

**Comment by bakito** [comment]
@diptripa 
Thank you for the feature request.
I'm currently don't have the capacity to work on this.
If you want to check it yourself, feel free to make a PR.

**Comment by christianknell** [comment]
I would give it a try. But let's talk about implementation details first so I don't implement stuff in the wrong way.

My suggestion to implement the cluster-scope: when there is no "namespace" set in the Secret field it automatically seals for the whole cluster. What do you think of that?

**Comment by dipeshtripathi** [comment]
> I would give it a try. But let's talk about implementation details first so I don't implement stuff in the wrong way.
> 
> My suggestion to implement the cluster-scope: when there is no "namespace" set in the Secret field it automatically seals for the whole cluster. What do you think of that?

Yes I think this would be a good option.
I was also thinking of removing the encode/decode option on the ui, it has the potential to confuse newbies.

**Comment by christianknell** [comment]
> Yes I think this would be a good option.
What do you think about the suggestion @bakito?

> I was also thinking of removing the encode/decode option on the ui, it has the potential to confuse newbies.
What would you suggest to use instead? I think we definitely need a button for encoding / decoding. You only want to seperate these two?

**Comment by bakito** [comment]
@christianknell adding an option for xluster scoped, seems ok for me. E.g. via a checkbox in the UI.

I agree in keeping the buttons unless there would be a better option. But this schould be handled separately

**Comment by christianknell** [comment]
@bakito: alright. I will try to find time between christmas and new year.

**Comment by adrianiacobghiula** [comment]
@bakito @christianknell you can now manage the scope by having the annotation on the secret 
```
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
```
